on:
  push:
    branches:
      - "*"
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Lua Install
        run: sudo apt-get install lua5.3 luajit
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - run: npm ci
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./benchmarks/benchmark_master.json
          key: ${{ runner.os }}-benchmark
      - name: Build benchmark
        run: npx typescript-to-lua -p tsconfig.json
        working-directory: benchmarks
      - name: Run benchmark Lua
        id: benchmark-lua
        run: echo ::set-output name=info::`lua -- main.lua ../benchmark_master.json`
        working-directory: benchmarks/dist
      - name: Run benchmark LuaJIT
        id: benchmark-jit
        run: echo ::set-output name=info::`luajit -- main.lua ../benchmark_master.json`
        working-directory: benchmarks/dist
      - name: Create benchmark check
        uses: actions/github-script@0.9.0
        with:
          benchmark_info_lua: ${{steps.benchmark-lua.outputs.info}}
          benchmark_info_jit: ${{steps.benchmark-jit.outputs.info}}
          script: |
            const benchmarkInfoLua = JSON.parse(core.getInput('benchmark_info_lua', { required: true }));
            const benchmarkInfoJIT = JSON.parse(core.getInput('benchmark_info_jit', { required: true }));

            const summary = `### Lua5.3\n${benchmarkInfoLua.summary}\n### LuaJIT\n${benchmarkInfoJIT.summary}`;

            const text = `### Lua5.3\n${benchmarkInfoLua.text}\n### LuaJIT\n${benchmarkInfoJIT.text}`;

            github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Benchmark results",
              head_sha: context.sha,
              status: "completed",
              conclusion: "neutral",
              output: {
                title: "Benchmark results",
                summary: summary,
                text: benchmarkInfo.text
              }
            });
