on:
  push:
    branches:
      - "*"
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Lua dependecies
        run: sudo apt-get install libreadline-dev
      - name: Lua download
        run: curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz
      - name: Lua extract
        run: tar -zxf lua-5.3.5.tar.gz
      - name: Lua install
        run: cd lua-5.3.5 && make linux test && sudo make install
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - run: npm ci
      # - name: Download previous benchmark data
      #   uses: actions/cache@v1
      #   with:
      #     path: ./benchmarks/benchmark_baseline.json
      #     key: ${{ runner.os }}-benchmark
      - name: Build benchmark
        run: npx typescript-to-lua -p tsconfig.json
        working-directory: benchmarks
      - name: Run benchmark
        id: benchmark
        run: echo ::set-output name=info::`lua -- main.lua ../benchmark_baseline.json`
        working-directory: benchmarks/dist
      - name: Create benchmark check
        uses: actions/github-script@0.9.0
        with:
          benchmark_info: ${{steps.benchmark.outputs.info}}
          script: |
            const benchmarkInfo = JSON.parse(core.getInput('benchmark_info', { required: true }));
            github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Benchmark results",
              head_sha: context.sha,
              status: "completed",
              conclusion: "neutral",
              output: {
                title: "Benchmark results",
                summary: benchmarkInfo.summary,
                text: benchmarkInfo.text
              }
            });
